sonar.projectKey=smartlogix-frontend
sonar.projectName=SmartLogix - Frontend Angular
sonar.projectVersion=1.0

# Rutas de código fuente y pruebas
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.test.ts
sonar.exclusions=node_modules/**,dist/**,src/**/*.spec.ts,src/**/*.test.ts,src/main.ts,src/main.server.ts,src/server.ts

# Codificación del código fuente
sonar.sourceEncoding=UTF-8

# Ruta del reporte de cobertura LCOV generado por Vitest
sonar.javascript.lcov.reportPaths=coverage/SmartLogix/lcov.info
